"""
tests/test_wizard.py
====================
Locating the gcloud SDK.

`shutil.which` answers "is gcloud on *this process's* PATH", which is not the
question. The SDK installer puts nothing on a system PATH -- it appends a
`source .../path.zsh.inc` line to the user's shell profile. So gcloud works in
the terminal and is invisible to the web UI (nohup), a GUI launch, systemd or
cron. Reading the profile is what actually answers it.

Found live: an SDK at `/Users/…/Repos/google-cloud-sdk 2/bin/gcloud` — outside
every standard location, and with a space in the path. Both properties are
covered below because both are what a real install looked like.
"""

from __future__ import annotations

import os
import stat

import pytest

import wizard


@pytest.fixture(autouse=True)
def isolate(monkeypatch):
    """No PATH hit, no standard-location hit, no env override, unless a test
    asks for one. Otherwise the developer's own gcloud decides the result."""
    monkeypatch.setattr(wizard.shutil, "which", lambda _n: None)
    monkeypatch.setattr(wizard, "_KNOWN", ())
    monkeypatch.setattr(wizard, "_PROFILES", ())
    monkeypatch.delenv("GCLOUD_BIN", raising=False)


def _make_sdk(root, name="google-cloud-sdk"):
    """A believable SDK layout: <root>/<name>/{path.zsh.inc,bin/gcloud}."""
    sdk = root / name
    (sdk / "bin").mkdir(parents=True)
    (sdk / "path.zsh.inc").write_text("# adds to PATH\n")
    exe = sdk / "bin" / "gcloud"
    exe.write_text("#!/bin/sh\necho hi\n")
    exe.chmod(exe.stat().st_mode | stat.S_IXUSR)
    return sdk, str(exe)


def _profile(tmp_path, sdk, name=".zshrc"):
    prof = tmp_path / name
    prof.write_text(
        "# generated by the SDK installer\n"
        f"if [ -f '{sdk}/path.zsh.inc' ]; then . '{sdk}/path.zsh.inc'; fi\n"
        f"if [ -f '{sdk}/completion.zsh.inc' ]; then . '{sdk}/completion.zsh.inc'; fi\n"
    )
    return str(prof)


class TestFindGcloud:
    def test_nothing_anywhere_reports_not_found(self):
        assert wizard.find_gcloud() == ("", "")

    def test_path_wins_when_present(self, monkeypatch, tmp_path):
        _, exe = _make_sdk(tmp_path)
        monkeypatch.setattr(wizard.shutil, "which", lambda _n: exe)
        assert wizard.find_gcloud() == (exe, "PATH")

    def test_explicit_env_override_beats_path(self, monkeypatch, tmp_path):
        _, exe = _make_sdk(tmp_path)
        _, other = _make_sdk(tmp_path, "other-sdk")
        monkeypatch.setattr(wizard.shutil, "which", lambda _n: other)
        monkeypatch.setenv("GCLOUD_BIN", exe)
        assert wizard.find_gcloud() == (exe, "GCLOUD_BIN")

    def test_found_via_shell_profile(self, monkeypatch, tmp_path):
        sdk, exe = _make_sdk(tmp_path)
        monkeypatch.setattr(wizard, "_PROFILES", (_profile(tmp_path, sdk),))

        path, how = wizard.find_gcloud()
        assert path == exe
        assert how == ".zshrc"

    def test_profile_path_containing_a_space(self, monkeypatch, tmp_path):
        """The real-world case: a second download is named 'google-cloud-sdk 2'.
        A shell-string implementation would split it into two arguments."""
        sdk, exe = _make_sdk(tmp_path, "google-cloud-sdk 2")
        monkeypatch.setattr(wizard, "_PROFILES", (_profile(tmp_path, sdk),))

        path, _ = wizard.find_gcloud()
        assert path == exe
        assert " " in path

    def test_double_quoted_profile_line(self, monkeypatch, tmp_path):
        sdk, exe = _make_sdk(tmp_path)
        prof = tmp_path / ".bash_profile"
        prof.write_text(f'source "{sdk}/path.bash.inc"\n')
        monkeypatch.setattr(wizard, "_PROFILES", (str(prof),))

        assert wizard.find_gcloud()[0] == exe

    def test_stale_profile_entry_is_skipped(self, monkeypatch, tmp_path):
        """An uninstalled SDK leaves its line behind. Pointing at a path that
        no longer exists must not be reported as found."""
        sdk, exe = _make_sdk(tmp_path)
        gone = tmp_path / "deleted-sdk"
        (gone).mkdir()
        prof = tmp_path / ".zshrc"
        prof.write_text(
            f". '{gone}/path.zsh.inc'\n"     # stale, no bin/gcloud under it
            f". '{sdk}/path.zsh.inc'\n"      # the real one
        )
        monkeypatch.setattr(wizard, "_PROFILES", (str(prof),))

        assert wizard.find_gcloud()[0] == exe

    def test_missing_profile_files_are_not_an_error(self, monkeypatch, tmp_path):
        monkeypatch.setattr(wizard, "_PROFILES",
                            (str(tmp_path / "nope"), str(tmp_path / "also-nope")))
        assert wizard.find_gcloud() == ("", "")

    def test_a_directory_named_gcloud_is_not_mistaken_for_the_binary(
            self, monkeypatch, tmp_path):
        sdk = tmp_path / "google-cloud-sdk"
        (sdk / "bin" / "gcloud").mkdir(parents=True)   # a directory, not a file
        (sdk / "path.zsh.inc").write_text("")
        monkeypatch.setattr(wizard, "_PROFILES", (_profile(tmp_path, sdk),))

        assert wizard.find_gcloud() == ("", "")

    def test_non_executable_file_is_rejected(self, monkeypatch, tmp_path):
        sdk = tmp_path / "google-cloud-sdk"
        (sdk / "bin").mkdir(parents=True)
        (sdk / "path.zsh.inc").write_text("")
        exe = sdk / "bin" / "gcloud"
        exe.write_text("#!/bin/sh\n")
        exe.chmod(0o644)
        monkeypatch.setattr(wizard, "_PROFILES", (_profile(tmp_path, sdk),))

        assert wizard.find_gcloud() == ("", "")

    def test_standard_locations_are_the_last_resort(self, monkeypatch, tmp_path):
        _, exe = _make_sdk(tmp_path)
        monkeypatch.setattr(wizard, "_KNOWN", (exe,))
        assert wizard.find_gcloud() == (exe, "standard location")


class TestGcloudReadyStep:
    def test_not_found_says_where_it_looked(self, monkeypatch):
        st = wizard.State.__new__(wizard.State)
        st.notes, st.gcloud = {}, ""

        assert st.gcloud_ready() is False
        note = st.notes["gcloud"]
        assert "PATH" in note and "profile" in note

    def test_found_but_unauthenticated_is_not_ready(self, monkeypatch, tmp_path):
        _, exe = _make_sdk(tmp_path)
        monkeypatch.setattr(wizard, "find_gcloud", lambda: (exe, "PATH"))
        monkeypatch.setattr(wizard, "sh", lambda *a, **k: (1, "no active account"))

        st = wizard.State.__new__(wizard.State)
        st.notes, st.gcloud = {}, ""

        assert st.gcloud_ready() is False
        # The fix must be in the message; "not ready" alone is useless.
        assert "gcloud auth login" in st.notes["gcloud"]

    def test_authenticated_reports_the_account(self, monkeypatch, tmp_path):
        _, exe = _make_sdk(tmp_path)
        monkeypatch.setattr(wizard, "find_gcloud", lambda: (exe, "PATH"))
        monkeypatch.setattr(wizard, "sh", lambda *a, **k: (0, "admin@example.com"))

        st = wizard.State.__new__(wizard.State)
        st.notes, st.gcloud = {}, ""

        assert st.gcloud_ready() is True
        assert "admin@example.com" in st.notes["gcloud"]
        assert st.gcloud == exe

    def test_non_path_discovery_is_disclosed(self, monkeypatch, tmp_path):
        """Found only via a profile means it works here but would not work
        from cron or a GUI launch -- the operator should be told which."""
        _, exe = _make_sdk(tmp_path)
        monkeypatch.setattr(wizard, "find_gcloud", lambda: (exe, ".zshrc"))
        monkeypatch.setattr(wizard, "sh", lambda *a, **k: (0, "admin@example.com"))

        st = wizard.State.__new__(wizard.State)
        st.notes, st.gcloud = {}, ""
        st.gcloud_ready()

        assert ".zshrc" in st.notes["gcloud"]

    def test_the_resolved_binary_is_what_gets_executed(self, monkeypatch, tmp_path):
        """Regression guard: calling the literal string "gcloud" instead of the
        resolved path is exactly the bug this whole module exists to fix."""
        _, exe = _make_sdk(tmp_path, "google-cloud-sdk 2")
        monkeypatch.setattr(wizard, "find_gcloud", lambda: (exe, ".zshrc"))
        seen = {}

        def fake_sh(cmd, **kw):
            seen["cmd"] = cmd
            return 0, "admin@example.com"

        monkeypatch.setattr(wizard, "sh", fake_sh)
        st = wizard.State.__new__(wizard.State)
        st.notes, st.gcloud = {}, ""
        st.gcloud_ready()

        assert seen["cmd"][0] == exe
        # argv list, never a shell string -- the space would split the path
        assert isinstance(seen["cmd"], list)


class TestCredentialsReadyAgreesWithTheUploader:
    """
    The wizard's step 3 and the step 3 panel must not disagree.

    They did: the panel wrote uploads to `Settings().source_sa_key` (default
    `./keys/source-sa.json`) while the wizard read `env["SOURCE_SA_KEY"]` with
    no default. Nothing writes that variable into env.sh, so a key uploaded to
    exactly the right place was shown as "✓ looks good" by the panel and
    "missing key file(s): source, target" by the rail beside it.

    One resolution path -- config.Settings -- is the fix, and these tests are
    what keeps them from drifting apart again.
    """

    SA = ('{"type":"service_account","project_id":"p","private_key_id":"x",'
          '"private_key":"-----BEGIN PRIVATE KEY-----\\nabc\\n-----END PRIVATE KEY-----\\n",'
          '"client_email":"sa@p.iam.gserviceaccount.com","client_id":"1"}')

    @pytest.fixture
    def paths(self, tmp_path, monkeypatch):
        keys = tmp_path / "keys"
        keys.mkdir()
        monkeypatch.setenv("SOURCE_SA_KEY", str(keys / "source-sa.json"))
        monkeypatch.setenv("TARGET_SA_KEY", str(keys / "target-sa.json"))
        monkeypatch.setenv("AUTH_MODE", "key")
        return keys

    def _state(self):
        st = wizard.State.__new__(wizard.State)
        st.env, st.notes, st.gcloud = {}, {}, ""
        st._preflight = None
        return st

    def test_uploaded_keys_are_seen_without_env_sh_naming_them(self, paths, monkeypatch):
        """The exact reported bug. env.sh says nothing about key paths; the
        files are at the Settings defaults; both views must agree."""
        (paths / "source-sa.json").write_text(self.SA)
        (paths / "target-sa.json").write_text(self.SA)

        st = self._state()
        assert st.credentials_ready() is True
        assert "both key files present" in st.notes["creds"]

    def test_missing_keys_are_still_reported(self, paths):
        st = self._state()
        assert st.credentials_ready() is False
        assert "source" in st.notes["creds"] and "target" in st.notes["creds"]

    def test_one_present_one_missing_names_only_the_missing_one(self, paths):
        (paths / "source-sa.json").write_text(self.SA)
        st = self._state()

        assert st.credentials_ready() is False
        note = st.notes["creds"]
        assert "target" in note and "source" not in note

    def test_an_empty_file_does_not_count_as_present(self, paths):
        (paths / "source-sa.json").write_text("")
        (paths / "target-sa.json").write_text(self.SA)
        st = self._state()
        assert st.credentials_ready() is False

    def test_oauth_mode_is_ready_only_when_both_tenants_consented(
            self, tmp_path, monkeypatch):
        """Previously unhandled: oauth mode fell through to the key-file check
        and reported missing keys that mode never uses."""
        monkeypatch.setenv("AUTH_MODE", "oauth")
        monkeypatch.setenv("OAUTH_TOKEN_DIR", str(tmp_path / "oauth"))
        monkeypatch.setenv("OAUTH_CLIENT_SECRETS", str(tmp_path / "cs.json"))
        (tmp_path / "cs.json").write_text("{}")

        import oauth_store

        store = oauth_store.TokenStore(str(tmp_path / "oauth"))
        st = self._state()

        assert st.credentials_ready() is False
        assert "not connected" in st.notes["creds"]

        store.save("source", {"refresh_token": "a", "account": "x@src"})
        st = self._state()
        assert st.credentials_ready() is False
        assert "target" in st.notes["creds"]

        store.save("target", {"refresh_token": "b", "account": "y@tgt"})
        st = self._state()
        assert st.credentials_ready() is True
        assert "both tenants connected" in st.notes["creds"]

    def test_oauth_mode_never_reports_missing_key_files(self, tmp_path, monkeypatch):
        monkeypatch.setenv("AUTH_MODE", "oauth")
        monkeypatch.setenv("OAUTH_TOKEN_DIR", str(tmp_path / "oauth"))
        monkeypatch.setenv("OAUTH_CLIENT_SECRETS", str(tmp_path / "absent.json"))

        st = self._state()
        st.credentials_ready()
        assert "key file" not in st.notes["creds"]

    def test_keyless_mode_needs_no_files(self, monkeypatch):
        monkeypatch.setenv("AUTH_MODE", "impersonate")
        monkeypatch.setenv("SOURCE_SA_EMAIL", "s@p.iam.gserviceaccount.com")
        monkeypatch.setenv("TARGET_SA_EMAIL", "t@p.iam.gserviceaccount.com")

        st = self._state()
        assert st.credentials_ready() is True
        assert "keyless" in st.notes["creds"]


class TestRunModes:
    """
    What is this run for?

    Without this the wizard presented one shape for every purpose: a real
    migration showed "seed the source tenant" as an outstanding task, and a
    seed-only run could never reach 100% because it was waiting on a migration
    nobody intended to perform.
    """

    def _state(self, tmp_path):
        st = wizard.State.__new__(wizard.State)
        st.env = {"MIGRATION_DB": str(tmp_path / "nope.db")}
        st.notes, st.gcloud, st._preflight = {}, "", False
        return st

    def test_migrate_only_skips_seeding(self, tmp_path):
        steps = wizard.build_steps(self._state(tmp_path), "migrate_only")
        assert [s["n"] for s in steps if s["state"] == wizard.SKIP] == [7]

    def test_seed_only_skips_the_migration_half(self, tmp_path):
        steps = wizard.build_steps(self._state(tmp_path), "seed_only")
        skipped = [s["n"] for s in steps if s["state"] == wizard.SKIP]
        assert skipped == [6, 8, 9]

    def test_seed_and_migrate_skips_nothing(self, tmp_path):
        steps = wizard.build_steps(self._state(tmp_path), "seed_and_migrate")
        assert [s["n"] for s in steps if s["state"] == wizard.SKIP] == []

    def test_a_skipped_step_says_why_rather_than_looking_incomplete(self, tmp_path):
        steps = wizard.build_steps(self._state(tmp_path), "migrate_only")
        seven = [s for s in steps if s["n"] == 7][0]
        assert seven["skipped"] is True
        assert seven["note"] == "not needed for this run"

    def test_an_unknown_mode_falls_back_to_migrating(self, tmp_path):
        """A typo in env.sh must not silently skip the migration itself."""
        steps = wizard.build_steps(self._state(tmp_path), "nonsense")
        assert [s["n"] for s in steps if s["state"] == wizard.SKIP] == [7]

    def test_the_mode_is_read_from_settings_when_not_passed(self, tmp_path, monkeypatch):
        monkeypatch.setenv("RUN_MODE", "seed_only")
        steps = wizard.build_steps(self._state(tmp_path))
        assert [s["n"] for s in steps if s["state"] == wizard.SKIP] == [6, 8, 9]

    def test_every_mode_leaves_at_least_one_actionable_step(self, tmp_path):
        for mode in wizard.RUN_MODES:
            steps = wizard.build_steps(self._state(tmp_path), mode)
            live = [s for s in steps if s["state"] != wizard.SKIP]
            assert live, f"{mode} skips everything"

    def test_seeding_is_never_skipped_when_it_was_asked_for(self, tmp_path):
        for mode in ("seed_only", "seed_and_migrate"):
            steps = wizard.build_steps(self._state(tmp_path), mode)
            seven = [s for s in steps if s["n"] == 7][0]
            assert seven["state"] != wizard.SKIP, mode
